/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traductor;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URLEncoder;
import java.util.ArrayList;
import javax.swing.text.html.HTML;
import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.client.HttpClient;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.impl.client.DefaultHttpClient;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Luis
 */
public class JFTraductor extends javax.swing.JFrame {
    
    

    /**
     * Creates new form JFTraductor
     */
    public JFTraductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jta_ingles_uno = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_ingles_dos = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_español_uno = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jta_español_dos = new javax.swing.JTextArea();
        btn_traducir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jta_ingles_uno.setColumns(20);
        jta_ingles_uno.setRows(5);
        jScrollPane1.setViewportView(jta_ingles_uno);

        jta_ingles_dos.setColumns(20);
        jta_ingles_dos.setRows(5);
        jScrollPane2.setViewportView(jta_ingles_dos);

        jta_español_uno.setColumns(20);
        jta_español_uno.setRows(5);
        jScrollPane3.setViewportView(jta_español_uno);

        jta_español_dos.setColumns(20);
        jta_español_dos.setRows(5);
        jScrollPane4.setViewportView(jta_español_dos);

        btn_traducir.setText("TRADUCIR");
        btn_traducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_traducirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btn_traducir)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(btn_traducir)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_traducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_traducirActionPerformed
        // TODO add your handling code here:
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
               jta_español_uno.setText(traducir(jta_ingles_uno.getText()));
               jta_español_dos.setText(traducir(jta_ingles_dos.getText()));
            }
        });
        thread.start();
        
        
        Thread thread_dos = new Thread(new Runnable() {
            @Override
            public void run() {
               
               jta_español_dos.setText(traducir(jta_ingles_dos.getText()));
            }
        });
        thread_dos.start();
        
    }//GEN-LAST:event_btn_traducirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTraductor().setVisible(true);
            }
        });
    }
    
    
    private String traducir(String texto){
        
        
          try {
              
              
            JSONObject jsonObject;
            //parametros para crear la url
            
            
            String api_key = "trnsl.1.1.20170626T004806Z.aa53b5594c53e1d3.2141ee8ec9e2360dceea20c0a9b8a5d46fdee5e9";
            String traduccion = "en-es";
        
            //indico url junto a los parametros
            //uso URLEncoder para que al mandar el texto salga algo como "my%20friend" y no "my friend" lo cual haria que mi url fuese invalida
            //NOTA: las weas que salen tachadas son weas "deprecated" o sea que son weas antiguas y que fueron cambiadas por otras formas de hacer lo mismo, pero aun asi funcionan.
            String uri = "https://translate.yandex.net/api/v1.5/tr.json/translate?lang="+traduccion+"&text="+URLEncoder.encode(texto)+"&key="+api_key;
            
            
            //creo el cliente http y post y le digo que se "meta" a mi url
            HttpClient httpClient = new DefaultHttpClient();
            HttpPost httpPost = new HttpPost(uri);
            httpPost.setEntity(new UrlEncodedFormEntity(new ArrayList<NameValuePair>()));
            HttpEntity httpEntity = httpClient.execute(httpPost).getEntity();
            
            //paso la respuesta de mi wea a un input stream pa leerlo y pasarloa un stream builder
            InputStream stream = httpEntity.getContent();
            BufferedReader bReader = new BufferedReader(new InputStreamReader(stream, "utf-8"), 8);
            StringBuilder sBuilder = new StringBuilder();

            String line = null;
            while ((line = bReader.readLine()) != null) {
                sBuilder.append(line + "\n");
            }

            stream.close();
            //convierto la respuesta de mi sbuilder a jsonObject
            jsonObject = new JSONObject(sBuilder.toString());
            //para tomar el parametro "text" del json, debo tomar el arreglo dentro de el
            JSONArray array = jsonObject.getJSONArray("text");
            //una vezz que tomo el arreglo, le digo que lea el primer indice y listo
            texto = String.valueOf(array.getString(0));
           
             /*
            mira m4n aber te esplico:
            
            primero hago la peticion del json con los siguientes datos: mi key, mi texto, y hacia que lenguaje quero traducir
            luego mediante un http client hago una peticion post a mi url
            despues no se que wa pasa pero no importa
            
            luego con el inputstream tomo el contenido del httpentity y lo paso a un bufferedreader, le digo que lea el stream y en formato utf-8
            despues recorro toda esa mierda y queda guardada en el sbuilder
            luego instanceo un JSONObject y le paso los datos del sbuilder (si en ese momento mostrase la respuesta que me dio la pagina seria algo coomo: {"code":200,"lang":"en-es","text":["eres un perdedor"]}
            
            despues creo una variable del tipo JSONArray y le digo que tome el array de "text" IMPORTANTE: text es un array, pero lo demas son objetos (perros qlos que me complican la vida, debieron ser todos objetos)
            finalmente digo que el string respuesta es igual al valor del array.getstring(0) (primer elemento del array)
            
            En caso de que el array "text" hubiese tenido objetis metidos dentro, la forma de consultarlos hubiese sido:
            
            jsonObject.getJSONArray("clientes").getJSONObject(0).getString("nombre")
            
            Como en este caso "text" es un array sin objetos, solo llamo al array y le digo que pesque el string que hay en el primer indice
            
            */
            
         
            System.out.println(texto);
           
        } catch (JSONException e) {
            e.printStackTrace();
            
        } catch (Exception e){
            e.printStackTrace();
        }
        
        
        
        return texto;
        
        
        //conchetumare que me costo la wea
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_traducir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jta_español_dos;
    private javax.swing.JTextArea jta_español_uno;
    private javax.swing.JTextArea jta_ingles_dos;
    private javax.swing.JTextArea jta_ingles_uno;
    // End of variables declaration//GEN-END:variables
}
